# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routing_umweltzone_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoutingUmweltzoneDialogBase(object):
    def setupUi(self, RoutingUmweltzoneDialogBase):
        RoutingUmweltzoneDialogBase.setObjectName("RoutingUmweltzoneDialogBase")
        RoutingUmweltzoneDialogBase.resize(355, 344)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        RoutingUmweltzoneDialogBase.setFont(font)
        RoutingUmweltzoneDialogBase.setStyleSheet("background-color:rgb(85, 255, 127)")
        self.button_box = QtWidgets.QDialogButtonBox(RoutingUmweltzoneDialogBase)
        self.button_box.setEnabled(True)
        self.button_box.setGeometry(QtCore.QRect(150, 290, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_box.setFont(font)
        self.button_box.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.Startpunkt = QtWidgets.QLabel(RoutingUmweltzoneDialogBase)
        self.Startpunkt.setGeometry(QtCore.QRect(20, 100, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.Startpunkt.setFont(font)
        self.Startpunkt.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.Startpunkt.setObjectName("Startpunkt")
        self.Zielpunkt = QtWidgets.QLabel(RoutingUmweltzoneDialogBase)
        self.Zielpunkt.setGeometry(QtCore.QRect(20, 150, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Zielpunkt.setFont(font)
        self.Zielpunkt.setStyleSheet("background-color: rgb(170, 170, 255);\n"
"")
        self.Zielpunkt.setMidLineWidth(3)
        self.Zielpunkt.setObjectName("Zielpunkt")
        self.Driver = QtWidgets.QLabel(RoutingUmweltzoneDialogBase)
        self.Driver.setGeometry(QtCore.QRect(20, 40, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Driver.setFont(font)
        self.Driver.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"gridline-color: rgb(0, 0, 0);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.Driver.setObjectName("Driver")
        self.pushButton = QtWidgets.QPushButton(RoutingUmweltzoneDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(250, 100, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton2 = QtWidgets.QPushButton(RoutingUmweltzoneDialogBase)
        self.pushButton2.setGeometry(QtCore.QRect(250, 150, 75, 23))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.pushButton2.setFont(font)
        self.pushButton2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.pushButton2.setObjectName("pushButton2")
        self.startRouting = QtWidgets.QLineEdit(RoutingUmweltzoneDialogBase)
        self.startRouting.setGeometry(QtCore.QRect(110, 100, 113, 20))
        self.startRouting.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.startRouting.setObjectName("startRouting")
        self.zielRouting = QtWidgets.QLineEdit(RoutingUmweltzoneDialogBase)
        self.zielRouting.setGeometry(QtCore.QRect(110, 150, 113, 20))
        self.zielRouting.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.zielRouting.setObjectName("zielRouting")
        self.comboBoxProfil = QtWidgets.QComboBox(RoutingUmweltzoneDialogBase)
        self.comboBoxProfil.setGeometry(QtCore.QRect(150, 40, 69, 22))
        self.comboBoxProfil.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.comboBoxProfil.setObjectName("comboBoxProfil")
        self.comboBoxProfil.addItem("")
        self.comboBoxProfil.addItem("")

        self.retranslateUi(RoutingUmweltzoneDialogBase)
        self.button_box.accepted.connect(RoutingUmweltzoneDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(RoutingUmweltzoneDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(RoutingUmweltzoneDialogBase)

    def retranslateUi(self, RoutingUmweltzoneDialogBase):
        _translate = QtCore.QCoreApplication.translate
        RoutingUmweltzoneDialogBase.setWindowTitle(_translate("RoutingUmweltzoneDialogBase", "Routing Umweltzone"))
        self.Startpunkt.setText(_translate("RoutingUmweltzoneDialogBase", "Startpunkt"))
        self.Zielpunkt.setText(_translate("RoutingUmweltzoneDialogBase", "Zielpunkt"))
        self.Driver.setText(_translate("RoutingUmweltzoneDialogBase", "Driver Profil"))
        self.pushButton.setText(_translate("RoutingUmweltzoneDialogBase", "suchen"))
        self.pushButton2.setText(_translate("RoutingUmweltzoneDialogBase", "suchen"))
        self.comboBoxProfil.setItemText(0, _translate("RoutingUmweltzoneDialogBase", "PKW"))
        self.comboBoxProfil.setItemText(1, _translate("RoutingUmweltzoneDialogBase", "LKW"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoutingUmweltzoneDialogBase = QtWidgets.QDialog()
    ui = Ui_RoutingUmweltzoneDialogBase()
    ui.setupUi(RoutingUmweltzoneDialogBase)
    RoutingUmweltzoneDialogBase.show()
    sys.exit(app.exec_())
